<mark>########################################## 08/01/2025 ########################
<mark>######################################## Friday ########################

In [ ]:
# 1. Create a numpy array with numpy array module and with data type integer and float
import numpy as np
array1 = np.array([1, 2, 3, 4, 5], dtype=int)
print(array1)
type(array1)
array2 = np.array([1, 2, 3, 4, 5], dtype=float)
print(array2)
type(array2)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


numpy.ndarray

In [ ]:
#2. Create a numpy array that have zero, one, two, three, four dimension respectively. Also, print the shape and dimension of that array
array3 = np.array([1, 2, 3, 4, 5])
print(array3)
print(array3.shape)
print(array3.ndim)

[1 2 3 4 5]
(5,)
1


In [ ]:
#2a. Two dimension array
array3_2d = np.array([[11, 12, 13, 14, 15],
                      [16, 17, 18, 19, 10]])
print(array3_2d )
print(array3_2d.shape)
print(array3_2d.ndim)

[[11 12 13 14 15]
 [16 17 18 19 10]]
(2, 5)
2


In [ ]:
#2b. Three dimension array
array3_3d = np.array([[[11, 12, 13, 14, 15],
                       [16, 17, 18, 19, 20],
                       [21, 22, 23, 24, 25]]])
print(array3_3d )
print(array3_3d.shape)
print(array3_3d.ndim)

[[[11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]]
(1, 3, 5)
3


In [ ]:
#2c. Four dimension array
array3_4d = np.array([[[[11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20],
                        [21, 22, 23, 24, 25],
                        [26, 27, 28, 29, 30]]]])
print(array3_4d )
print(array3_4d.shape)
print(array3_4d.ndim)

[[[[11 12 13 14 15]
   [16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]]]
(1, 1, 4, 5)
4


In [ ]:
#3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy
array4 = np.identity(2)
print(array4)
array5 = np.identity(3)
print(array5)
array6 = np.identity(4)
print(array6)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#4. create a numpy array with shape 2x5 that has all element as zero
array7 = np.zeros((2, 5))
print(array7)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#5. Create a numpy array that has a 3x5 and all the element are 5
array8 = np.full((3, 5), 5)
print(array8)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
#6. Create a numpy array with random integers in the range of 0 - 100 and the sample size should be 25
array9 = np.random.randint(0, 100, 25)
print(array9)

[76 35 34 44 81 49 20 27 92  7 36 48 28 65 45  3 99 80  7 74 13 74 27 43
 35]


In [ ]:
#7 Create a numpy array in the shape of 2x3 with randomintegers from 1-100. Reshape the array in the shape of 3x2 and
#  print the updated shape and the resultant array
array10 = np.random.randint(1, 100, (2, 3))
print(array10)

[[30 95 98]
 [50 27 22]]


In [ ]:
#reshape to 3x2
reshaped_array = array10.reshape(3, 2)
print(reshaped_array)

[[30 95]
 [98 50]
 [27 22]]


In [ ]:
#8. Step 1. Create a random array with the range 0-1000, with a size 50 and
#   Step 2. Perform the below operation
#           a. Print the 10 elements of the array
#           b. Print the last 10 elements of the array
#           c. Print the element from indexes 10 - 25
#           d. Print the element at index 22
#           e. Print the array using negative indexes

array11 = np.random.randint(0, 1000, 50)
print(array11)

[458 258 764 410  63 427 795 124 803 346 321  20 369 237 364 272 119 293
 466 137 897 137 680 663 974 942 774 694 179 731 581  78 602 672 138 820
 898 388 707  29 480 348 229 127  17 511 897 345 272 202]


In [ ]:
#8 2a Print the 10 elements of the array
print(array11[:10])

[458 258 764 410  63 427 795 124 803 346]


In [ ]:
#8 2b. Print the last 10 elements of the array
print(array11[-10:])

[480 348 229 127  17 511 897 345 272 202]


In [ ]:
#8 2c.Print the element from indexes 10 - 25
print(array11[10:26])

[321  20 369 237 364 272 119 293 466 137 897 137 680 663 974 942]


In [ ]:
#8 2d. Print the element at index 22
print(array11[22])

680


In [ ]:
#8 2e.Print the array using negative indexes
print(array11[-1])

202


In [ ]:
#9. Given a numpy array that has values = [1, 2, 3, 4 ,5]. Perform the following operation
#a. insert the element 6 at the end of the array
#b. insert the element 10 at the beginning of the array
#c. insert the element before 4
#d. update the element 5 as 50
#e. Delete the element 50 in the updated array
#f. create the function to search for the element 30
#g. Sort the array in ascending order

#9a. insert the element 6 at the end of the array
array12 = np.array([1, 2, 3, 4, 5])
array12 = np.append(array12, 6)
print(array12)

[1 2 3 4 5 6]


In [ ]:
#9b. Insert the element 10 at the beginning of the array
array12 = np.insert(array12, 0, 10)
print(array12)

[10  1  2  3  4  5  6]


In [ ]:
#9c. insert the element before 4
array12 = np.insert(array12, 3, 11)
print(array12)

[10  1  2 11  3  4  5  6]


In [ ]:
#9d. update the element 5 as 50
array12[array12 == 5] = 50
print(array12)

[10  1  2 11  3  4 50  6]


In [ ]:
#9e. Delete the element 50 in the updated array
array12 = np.delete(array12, np.where(array12 == 50))
print(array12)

[10  1  2 11  3  4  6]


In [ ]:
#9f. create the function to search for the element 30
def search_element(array, element):
    if element in array:
        return f"Element {element} found in the array."
    else:
        return f"Element {element} not found in the array."

search_element(array12, 30)

'Element 30 not found in the array.'

In [ ]:
#9g. Sort the array in ascending order
sorted_array_asc = np.sort(array12)
print(sorted_array_asc)

[ 1  2  3  4  6 10 11]


In [ ]:
#9g(a) Sort the array in descending order
sorted_array_desc = np.sort(array12)[::-1]
print(sorted_array_desc)

[11 10  6  4  3  2  1]
