<mark>################################09/06/2025##############################
<mark>################################ Saturday ##############################
# LINEAR ALGEBRA

Linear algebra is a branch of mathematics that deals with linear equations, vector spaces, and their representations through matrices.
Definition and Components
Linear algebra focuses on the study of vectors, matrices, and linear transformations. It involves understanding how to manipulate these mathematical objects to solve systems of linear equations. The key components of linear algebra include:
Vectors: Quantities that have both magnitude and direction. They can be represented as points in space or as arrows in a coordinate system.
Matrices: Rectangular arrays of numbers that represent linear transformations and can be used to solve systems of linear equations.
Linear Equations: Equations that describe straight lines or hyperplanes in higher dimensions.

They can be expressed in the form

Ax = b

Ax=b, where A is a matrix, x is a vector of variables, and b is a result vector.
Applications

# Mathematics for Machine Learning

## Vector and Matrices

Lays the foundation for Machine Learning

Linear Algebra is going to be used in

**1. Machine Learning**

**2. Deep Learning**

It helps us to represent the data in Mathematical Terms.

Core Data Types in Linear Algebr

1. **Scalar** - A single numeric value - 0D

2. **Vector** - A one-dimensional array of scalars - 1D

3. **Matrix** - A two-dimensional array of scalars (rows × columns) - 2D

4. **Tensor** - A multi-dimensional generalization of matrices - 3D+

In ML and DL we can use these following types of datasets to work on

1. Tabular Data
Format: Structured rows/columns
Common Use: Business analytics, forecasting

2. Images - 2D arrays of pixel values (grayscale or RGB),
Format: 2D/3D arrays
Common Use: Computer vision, medical imaging

3. Videos - Sequence of images + audio over time
Format: Time-sequenced frames
Common Use: Action recognition, surveillance

4. Audio - 1D time-series signal (waveform)
Format: 1D waveform or spectrogram
Common Use: Speech recognition, music analysis

5. Signal - Time-series or spatial data (e.g., ECG, sensor readings)
Format: Time-series or spatial
Common Use: IoT, ECG, seismic analysis, signals from Satellite

6. Text -


Other datatypes are Graph Data, Time-Series, Geospatial Data, Textual Data, Multimodal Data, Synthetic Data, and Streaming Data


All these are used as data in the ML and DL. ML use these data to give prediction

It is important to note Machine learning are entirely Mathematical. All the Machine Learning Technique you are going to study are based on Mathematical Formula or/and equation. Using Formulas and equations ML makes the prediction.

ML and DL are designed by Mathematicians not computer scientist, that being said, any of the data that is in the form of Images, Videos, Audio, and Signal cannot be passed to the mathematical formula or equation. Equations and Numbers only accept numbers

This is where the Linear Algebra comes in play to help us represent these data (Images, Videos, Audio, and Signal) in numerical form so that we can use them with Machine Learning..


In [ ]:
import numpy as np

r = 5  # magnitude
theta_deg = 45
theta_rad = np.deg2rad(theta_deg)

x = r * np.cos(theta_rad)
y = r * np.sin(theta_rad)

vector = np.array([x, y])
print("Vector:", vector)

Vector: [3.53553391 3.53553391]


In [ ]:
import numpy as np

tan_theta = 2.175
theta_rad = np.arctan(tan_theta)
theta_deg = np.degrees(theta_rad)

print("Angle in radians:", theta_rad)
print("Angle in degrees:", theta_deg)

Angle in radians: 1.13984733939452
Angle in degrees: 65.30844183652194


## Matrix

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

vector_Sample_1 = np.arange(5)
print(vector_Sample_1)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4]


In [ ]:
vector_Sample_1.ndim

1

In [ ]:
matrix_sample_1 = np.arange(9).reshape(3,3)
print(matrix_sample_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Addition & Subtraction**

In [ ]:
import numpy as np

# Define two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Matrix Addition
add_result = A + B

# Matrix Subtraction
sub_result = A - B

# Display results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition (A + B):\n", add_result)
print("Subtraction (A - B):\n", sub_result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


**Hadamard Multiplication / Array Multiplcation**

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Hadamard (element-wise) multiplication
C = A * B

print("Hadamard Product:\n", C)

Hadamard Product:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


**Matrix Multiplication**

In [ ]:
import numpy as np

# Define two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Matrix multiplication using @ operator
C = A @ B  # or np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication (A @ B):\n", C)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix Multiplication (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import numpy as np
lin_matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
np.linalg.matrix_rank(lin_matrix)

np.int64(2)

Row 1: [0, 1, 2]

Row 2: [3, 4, 5]

Row 3: [6, 7, 8]

Try expressing Row 2 as a combination of Row 1:

• 	Is Row 2 = Row 1 × scalar + constant?

Not quite. The difference between corresponding elements is not consistent:

• 	3 - 0 = 3

• 	4 - 1 = 3

• 	5 - 2 = 3

So yes, Row 2 is Row 1 + [3, 3, 3], but adding a constant vector is not a linear combination in the strict sense.

## Determinant

In [ ]:
np.linalg.det(lin_matrix)

np.float64(0.0)

In [ ]:
mat2 = np.random.randint(10, 51, size=(5,5))
mat2

array([[49, 32, 21, 39, 48],
       [16, 10, 14, 28, 31],
       [19, 20, 31, 48, 32],
       [22, 40, 13, 17, 12],
       [13, 11, 27, 47, 35]])

In [ ]:
np.linalg.det(mat2)

np.float64(385274.9999999993)

In [20]:
np.linalg.inv(mat2)

array([[ 0.08068782, -0.17019532, -0.04871845, -0.0230926 ,  0.09254688],
       [-0.02500811,  0.03785608, -0.03244436,  0.04791383,  0.01400298],
       [-0.17188502,  0.55775225,  0.65993122, -0.10482642, -0.82570631],
       [ 0.15112582, -0.53442346, -0.49672312,  0.0695607 ,  0.6963857 ],
       [-0.09245344,  0.33870612,  0.18623061, -0.01902537, -0.30837713]])

# <mark># Continue in the Word Document